# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    set ::env(RT_TMP) "./.Xil/Vivado-31562-graces.andrew.local.cmu.edu/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7vx485tffg1761-2

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv {
      /afs/ece.cmu.edu/usr/sohils/Private/18545/hdmi_test/hdmi_test.srcs/sources_1/new/video_unit.sv
      /afs/ece.cmu.edu/usr/sohils/Private/18545/hdmi_test/hdmi_test.srcs/sources_1/imports/gameboy/HDMI.sv
      /afs/ece.cmu.edu/usr/sohils/Private/18545/hdmi_test/hdmi_test.srcs/sources_1/imports/gameboy/constants.sv
      /afs/ece.cmu.edu/usr/sohils/Private/18545/hdmi_test/hdmi_test.srcs/sources_1/imports/gameboy/I2C.sv
      /afs/ece.cmu.edu/usr/sohils/Private/18545/hdmi_test/hdmi_test.srcs/sources_1/imports/gameboy/chipinterface.sv
    }
      rt::read_verilog {
      /afs/ece.cmu.edu/usr/sohils/Private/18545/hdmi_test/hdmi_test.srcs/sources_1/bd/framebuffer/hdl/framebuffer.v
      /afs/ece.cmu.edu/usr/sohils/Private/18545/hdmi_test/hdmi_test.srcs/sources_1/bd/clock/ip/clock_clk_wiz_0_0/clock_clk_wiz_0_0_clk_wiz.v
      /afs/ece.cmu.edu/usr/sohils/Private/18545/hdmi_test/hdmi_test.srcs/sources_1/bd/clock/ip/clock_clk_wiz_0_0/clock_clk_wiz_0_0.v
      /afs/ece.cmu.edu/usr/sohils/Private/18545/hdmi_test/hdmi_test.srcs/sources_1/bd/clock/hdl/clock.v
      /afs/ece.cmu.edu/usr/sohils/Private/18545/hdmi_test/hdmi_test.srcs/sources_1/bd/framebuffer/hdl/framebuffer_wrapper.v
      /afs/ece.cmu.edu/usr/sohils/Private/18545/hdmi_test/hdmi_test.srcs/sources_1/bd/clock/hdl/clock_wrapper.v
    }
      rt::read_vhdl -lib blk_mem_gen_v8_2 {
      /afs/ece.cmu.edu/usr/sohils/Private/18545/hdmi_test/hdmi_test.srcs/sources_1/ipshared/xilinx.com/blk_mem_gen_v8_2/7b054ed9/hdl/blk_mem_gen_v8_2_vhsyn_rfs.vhd
      /afs/ece.cmu.edu/usr/sohils/Private/18545/hdmi_test/hdmi_test.srcs/sources_1/ipshared/xilinx.com/blk_mem_gen_v8_2/7b054ed9/hdl/blk_mem_gen_v8_2.vhd
    }
      rt::read_vhdl -lib xil_defaultlib /afs/ece.cmu.edu/usr/sohils/Private/18545/hdmi_test/hdmi_test.srcs/sources_1/bd/framebuffer/ip/framebuffer_blk_mem_gen_0_0/synth/framebuffer_blk_mem_gen_0_0.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top ChipInterface
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
    rt::set_parameter webTalkPath {}
    rt::set_parameter enableSplitFlowPath "./.Xil/Vivado-31562-graces.andrew.local.cmu.edu/"
    if {$rt::useElabCache == false} {
      rt::run_rtlelab -module $rt::top
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }

    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
    }


    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
