
set_property PACKAGE_PIN AU23 [get_ports HDMI_TX_CLK]
set_property IOSTANDARD LVCMOS18 [get_ports HDMI_TX_CLK]
set_property PACKAGE_PIN AP21 [get_ports HDMI_TX_DE]
set_property IOSTANDARD LVCMOS18 [get_ports HDMI_TX_DE]
set_property IOSTANDARD LVCMOS18 [get_ports HDMI_TX_HS]
set_property PACKAGE_PIN AT22 [get_ports HDMI_TX_VS]
set_property IOSTANDARD LVCMOS18 [get_ports HDMI_TX_VS]
set_property PACKAGE_PIN AU22 [get_ports HDMI_TX_HS]
set_property PACKAGE_PIN AT35 [get_ports I2C_SCL]
set_property IOSTANDARD LVCMOS18 [get_ports I2C_SCL]
set_property PACKAGE_PIN AU32 [get_ports I2C_SDA]
set_property IOSTANDARD LVCMOS18 [get_ports I2C_SDA]
set_property PACKAGE_PIN E19 [get_ports SYSCLK_P]
set_property IOSTANDARD LVDS [get_ports SYSCLK_P]
set_property PACKAGE_PIN AV39 [get_ports rst]
set_property IOSTANDARD LVCMOS18 [get_ports rst]

set_property PACKAGE_PIN AM22 [get_ports {HDMI_TX_D[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {HDMI_TX_D[0]}]
set_property PACKAGE_PIN AL22 [get_ports {HDMI_TX_D[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {HDMI_TX_D[1]}]
set_property PACKAGE_PIN AJ20 [get_ports {HDMI_TX_D[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {HDMI_TX_D[2]}]
set_property PACKAGE_PIN AJ21 [get_ports {HDMI_TX_D[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {HDMI_TX_D[3]}]
set_property PACKAGE_PIN AM21 [get_ports {HDMI_TX_D[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {HDMI_TX_D[4]}]
set_property PACKAGE_PIN AL21 [get_ports {HDMI_TX_D[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {HDMI_TX_D[5]}]
set_property PACKAGE_PIN AK22 [get_ports {HDMI_TX_D[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {HDMI_TX_D[6]}]
set_property PACKAGE_PIN AJ22 [get_ports {HDMI_TX_D[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {HDMI_TX_D[7]}]
set_property PACKAGE_PIN AL20 [get_ports {HDMI_TX_D[8]}]
set_property IOSTANDARD LVCMOS18 [get_ports {HDMI_TX_D[8]}]
set_property PACKAGE_PIN AK20 [get_ports {HDMI_TX_D[9]}]
set_property IOSTANDARD LVCMOS18 [get_ports {HDMI_TX_D[9]}]
set_property PACKAGE_PIN AK23 [get_ports {HDMI_TX_D[10]}]
set_property IOSTANDARD LVCMOS18 [get_ports {HDMI_TX_D[10]}]
set_property PACKAGE_PIN AJ23 [get_ports {HDMI_TX_D[11]}]
set_property IOSTANDARD LVCMOS18 [get_ports {HDMI_TX_D[11]}]
set_property PACKAGE_PIN AN21 [get_ports {HDMI_TX_D[12]}]
set_property IOSTANDARD LVCMOS18 [get_ports {HDMI_TX_D[12]}]
set_property PACKAGE_PIN AP22 [get_ports {HDMI_TX_D[13]}]
set_property IOSTANDARD LVCMOS18 [get_ports {HDMI_TX_D[13]}]
set_property PACKAGE_PIN AP23 [get_ports {HDMI_TX_D[14]}]
set_property IOSTANDARD LVCMOS18 [get_ports {HDMI_TX_D[14]}]
set_property PACKAGE_PIN AN23 [get_ports {HDMI_TX_D[15]}]
set_property IOSTANDARD LVCMOS18 [get_ports {HDMI_TX_D[15]}]
set_property PACKAGE_PIN AM23 [get_ports {HDMI_TX_D[16]}]
set_property IOSTANDARD LVCMOS18 [get_ports {HDMI_TX_D[16]}]
set_property PACKAGE_PIN AN24 [get_ports {HDMI_TX_D[17]}]
set_property IOSTANDARD LVCMOS18 [get_ports {HDMI_TX_D[17]}]
set_property PACKAGE_PIN AY24 [get_ports {HDMI_TX_D[18]}]
set_property IOSTANDARD LVCMOS18 [get_ports {HDMI_TX_D[18]}]
set_property PACKAGE_PIN BB22 [get_ports {HDMI_TX_D[19]}]
set_property IOSTANDARD LVCMOS18 [get_ports {HDMI_TX_D[19]}]
set_property PACKAGE_PIN BA22 [get_ports {HDMI_TX_D[20]}]
set_property IOSTANDARD LVCMOS18 [get_ports {HDMI_TX_D[20]}]
set_property PACKAGE_PIN BA25 [get_ports {HDMI_TX_D[21]}]
set_property IOSTANDARD LVCMOS18 [get_ports {HDMI_TX_D[21]}]
set_property PACKAGE_PIN AY25 [get_ports {HDMI_TX_D[22]}]
set_property IOSTANDARD LVCMOS18 [get_ports {HDMI_TX_D[22]}]
set_property PACKAGE_PIN AY22 [get_ports {HDMI_TX_D[23]}]
set_property IOSTANDARD LVCMOS18 [get_ports {HDMI_TX_D[23]}]
set_property PACKAGE_PIN AY23 [get_ports {HDMI_TX_D[24]}]
set_property IOSTANDARD LVCMOS18 [get_ports {HDMI_TX_D[24]}]
set_property PACKAGE_PIN AV24 [get_ports {HDMI_TX_D[25]}]
set_property IOSTANDARD LVCMOS18 [get_ports {HDMI_TX_D[25]}]
set_property PACKAGE_PIN AU24 [get_ports {HDMI_TX_D[26]}]
set_property IOSTANDARD LVCMOS18 [get_ports {HDMI_TX_D[26]}]
set_property PACKAGE_PIN AW21 [get_ports {HDMI_TX_D[27]}]
set_property IOSTANDARD LVCMOS18 [get_ports {HDMI_TX_D[27]}]
set_property PACKAGE_PIN AV21 [get_ports {HDMI_TX_D[28]}]
set_property IOSTANDARD LVCMOS18 [get_ports {HDMI_TX_D[28]}]
set_property PACKAGE_PIN AT24 [get_ports {HDMI_TX_D[29]}]
set_property IOSTANDARD LVCMOS18 [get_ports {HDMI_TX_D[29]}]
set_property PACKAGE_PIN AR24 [get_ports {HDMI_TX_D[30]}]
set_property IOSTANDARD LVCMOS18 [get_ports {HDMI_TX_D[30]}]
set_property PACKAGE_PIN AU21 [get_ports {HDMI_TX_D[31]}]
set_property IOSTANDARD LVCMOS18 [get_ports {HDMI_TX_D[31]}]
set_property PACKAGE_PIN AT21 [get_ports {HDMI_TX_D[32]}]
set_property IOSTANDARD LVCMOS18 [get_ports {HDMI_TX_D[32]}]
set_property PACKAGE_PIN AW22 [get_ports {HDMI_TX_D[33]}]
set_property IOSTANDARD LVCMOS18 [get_ports {HDMI_TX_D[33]}]
set_property PACKAGE_PIN AW23 [get_ports {HDMI_TX_D[34]}]
set_property IOSTANDARD LVCMOS18 [get_ports {HDMI_TX_D[34]}]
set_property PACKAGE_PIN AV23 [get_ports {HDMI_TX_D[35]}]
set_property IOSTANDARD LVCMOS18 [get_ports {HDMI_TX_D[35]}]

set_property PULLUP true [get_ports I2C_SCL]
set_property PULLUP true [get_ports I2C_SDA]

set_property PACKAGE_PIN AY42 [get_ports en_bus]
set_property IOSTANDARD LVCMOS18 [get_ports en_bus]
set_property PACKAGE_PIN AT32 [get_ports USB_CTS]
set_property PACKAGE_PIN AR34 [get_ports USB_RTS]
set_property PACKAGE_PIN AU33 [get_ports USB_RX]
set_property PACKAGE_PIN AU36 [get_ports USB_TX]
set_property IOSTANDARD LVCMOS18 [get_ports USB_RTS]
set_property IOSTANDARD LVCMOS18 [get_ports USB_CTS]
set_property IOSTANDARD LVCMOS18 [get_ports USB_RX]
set_property IOSTANDARD LVCMOS18 [get_ports USB_TX]


set_property PACKAGE_PIN AM39 [get_ports {LEDS[0]}]
set_property PACKAGE_PIN AN39 [get_ports {LEDS[1]}]
set_property PACKAGE_PIN AR37 [get_ports {LEDS[2]}]
set_property PACKAGE_PIN AT37 [get_ports {LEDS[3]}]
set_property PACKAGE_PIN AR35 [get_ports {LEDS[4]}]
set_property PACKAGE_PIN AP41 [get_ports {LEDS[5]}]
set_property PACKAGE_PIN AP42 [get_ports {LEDS[6]}]
set_property PACKAGE_PIN AU39 [get_ports {LEDS[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {LEDS[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {LEDS[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {LEDS[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {LEDS[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {LEDS[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {LEDS[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {LEDS[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {LEDS[0]}]




set_property PACKAGE_PIN AV30 [get_ports bp_done]
set_property IOSTANDARD LVCMOS18 [get_ports bp_done]
set_property PACKAGE_PIN AY33 [get_ports drawn]
set_property IOSTANDARD LVCMOS18 [get_ports drawn]
set_property PACKAGE_PIN BA31 [get_ports fp_done]
set_property IOSTANDARD LVCMOS18 [get_ports fp_done]
set_property PACKAGE_PIN AW40 [get_ports push]
set_property IOSTANDARD LVCMOS18 [get_ports push]
set_property IOSTANDARD LVCMOS18 [get_ports {sel[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {sel[0]}]

set_property PACKAGE_PIN BA32 [get_ports {sel[0]}]
set_property PACKAGE_PIN AW30 [get_ports {sel[1]}]


set_property MARK_DEBUG true [get_nets recv/byte_ready]
set_property MARK_DEBUG true [get_nets {recv/D[0]}]
set_property MARK_DEBUG true [get_nets {prot/uart_byte_reg[7][0]}]
set_property MARK_DEBUG true [get_nets {prot/uart_byte_reg[7][1]}]
set_property MARK_DEBUG true [get_nets {prot/uart_byte_reg[7][2]}]
set_property MARK_DEBUG true [get_nets {prot/uart_byte_reg[7][3]}]
set_property MARK_DEBUG true [get_nets {prot/uart_byte_reg[7][4]}]
set_property MARK_DEBUG true [get_nets {prot/uart_byte_reg[7][5]}]
set_property MARK_DEBUG true [get_nets {prot/uart_byte_reg[7][6]}]
set_property MARK_DEBUG true [get_nets {prot/uart_byte_reg[7][7]}]
set_property MARK_DEBUG true [get_nets prot/shift]
set_property MARK_DEBUG false [get_nets {prot/count[10]}]
set_property MARK_DEBUG false [get_nets {prot/count[11]}]
set_property MARK_DEBUG false [get_nets {prot/count[12]}]
set_property MARK_DEBUG false [get_nets {prot/count[13]}]
set_property MARK_DEBUG false [get_nets {prot/count[14]}]
set_property MARK_DEBUG false [get_nets {prot/count[15]}]
set_property MARK_DEBUG false [get_nets {prot/count[2]}]
set_property MARK_DEBUG false [get_nets {prot/count[3]}]
set_property MARK_DEBUG false [get_nets {prot/count[4]}]
set_property MARK_DEBUG false [get_nets {prot/count[5]}]
set_property MARK_DEBUG false [get_nets {prot/count[6]}]
set_property MARK_DEBUG false [get_nets {prot/count[7]}]
set_property MARK_DEBUG false [get_nets {prot/count[8]}]
set_property MARK_DEBUG false [get_nets {prot/count[9]}]
set_property MARK_DEBUG true [get_nets {prot/data_count[0]}]
set_property MARK_DEBUG true [get_nets {prot/data_count[6]}]
set_property MARK_DEBUG true [get_nets {prot/data_count[7]}]
set_property MARK_DEBUG true [get_nets {prot/data_count[8]}]
set_property MARK_DEBUG true [get_nets {prot/data_count[9]}]
set_property MARK_DEBUG true [get_nets {prot/data_count_reg[5]_0[0]}]
set_property MARK_DEBUG true [get_nets {prot/data_count_reg[5]_0[1]}]
set_property MARK_DEBUG true [get_nets {prot/data_count_reg[5]_0[2]}]
set_property MARK_DEBUG true [get_nets {prot/data_count_reg[5]_0[3]}]
set_property MARK_DEBUG true [get_nets {prot/data_count_reg[5]_0[4]}]
connect_debug_port u_ila_0/probe1 [get_nets [list {prot/uart_byte_reg[7][0]} {prot/uart_byte_reg[7][1]} {prot/uart_byte_reg[7][2]} {prot/uart_byte_reg[7][3]} {prot/uart_byte_reg[7][4]} {prot/uart_byte_reg[7][5]} {prot/uart_byte_reg[7][6]} {prot/uart_byte_reg[7][7]}]]
connect_debug_port u_ila_0/probe3 [get_nets [list {prot/data_count_reg[5]_0[0]} {prot/data_count_reg[5]_0[1]} {prot/data_count_reg[5]_0[2]} {prot/data_count_reg[5]_0[3]} {prot/data_count_reg[5]_0[4]}]]

set_property MARK_DEBUG true [get_nets {prot/cs[2]}]
set_property MARK_DEBUG true [get_nets {prot/cs[1]}]
set_property MARK_DEBUG true [get_nets {prot/cs[0]}]
set_property MARK_DEBUG true [get_nets {recv/Q[7]}]
set_property MARK_DEBUG true [get_nets {recv/Q[6]}]
set_property MARK_DEBUG true [get_nets {recv/Q[5]}]
set_property MARK_DEBUG true [get_nets {recv/Q[4]}]
set_property MARK_DEBUG true [get_nets {recv/Q[3]}]
set_property MARK_DEBUG true [get_nets {recv/Q[2]}]
set_property MARK_DEBUG true [get_nets {recv/Q[1]}]
set_property MARK_DEBUG true [get_nets {recv/Q[0]}]
connect_debug_port u_ila_0_0/probe5 [get_nets [list prot/shift]]


set_property MARK_DEBUG true [get_nets {prot/timeout[10]_i_1_n_0}]
set_property MARK_DEBUG true [get_nets {prot/timeout[10]_i_4_n_0}]
set_property MARK_DEBUG true [get_nets {prot/timeout[2]_i_1_n_0}]
set_property MARK_DEBUG true [get_nets {prot/timeout[3]_i_1_n_0}]
set_property MARK_DEBUG true [get_nets {prot/timeout[4]_i_1_n_0}]
set_property MARK_DEBUG true [get_nets {prot/timeout[5]_i_1_n_0}]
set_property MARK_DEBUG true [get_nets {prot/timeout[5]_i_2_n_0}]
set_property MARK_DEBUG true [get_nets {prot/timeout[6]_i_1_n_0}]
set_property MARK_DEBUG true [get_nets {prot/timeout[7]_i_1_n_0}]
set_property MARK_DEBUG true [get_nets {prot/timeout[8]_i_1_n_0}]
set_property MARK_DEBUG true [get_nets {prot/timeout[9]_i_1_n_0}]
set_property MARK_DEBUG true [get_nets {prot/timeout[9]_i_2_n_0}]
connect_debug_port u_ila_0_0/probe5 [get_nets [list {prot/timeout[2]_i_1_n_0}]]
connect_debug_port u_ila_0_0/probe6 [get_nets [list {prot/timeout[3]_i_1_n_0}]]
connect_debug_port u_ila_0_0/probe7 [get_nets [list {prot/timeout[4]_i_1_n_0}]]
connect_debug_port u_ila_0_0/probe8 [get_nets [list {prot/timeout[5]_i_1_n_0}]]
connect_debug_port u_ila_0_0/probe10 [get_nets [list {prot/timeout[6]_i_1_n_0}]]
connect_debug_port u_ila_0_0/probe11 [get_nets [list {prot/timeout[7]_i_1_n_0}]]
connect_debug_port u_ila_0_0/probe12 [get_nets [list {prot/timeout[8]_i_1_n_0}]]
connect_debug_port u_ila_0_0/probe13 [get_nets [list {prot/timeout[9]_i_1_n_0}]]
connect_debug_port u_ila_0_0/probe15 [get_nets [list {prot/timeout[10]_i_1_n_0}]]
connect_debug_port u_ila_0_0/probe16 [get_nets [list {prot/timeout[10]_i_4_n_0}]]

connect_debug_port u_ila_0/probe2 [get_nets [list {prot/timeout_reg[0]} {prot/timeout_reg[1]} {prot/timeout_reg[2]} {prot/timeout_reg[3]} {prot/timeout_reg[4]} {prot/timeout_reg[5]} {prot/timeout_reg[6]} {prot/timeout_reg[7]} {prot/timeout_reg[8]} {prot/timeout_reg[9]} {prot/timeout_reg[10]} {prot/timeout_reg[11]} {prot/timeout_reg[12]} {prot/timeout_reg[13]} {prot/timeout_reg[14]} {prot/timeout_reg[15]}]]

connect_debug_port u_ila_0_0/probe3 [get_nets [list {prot/data_count[0]} {prot/data_count[1]} {prot/data_count[2]} {prot/data_count[3]} {prot/data_count[4]} {prot/data_count[5]} {prot/data_count[6]} {prot/data_count[7]} {prot/data_count[8]} {prot/data_count[9]}]]

connect_debug_port u_ila_0/clk [get_nets [list uart_sampling_clk_BUFG]]
connect_debug_port u_ila_0/probe0 [get_nets [list {data_count[0]} {data_count[1]} {data_count[2]} {data_count[3]} {data_count[4]} {data_count[5]} {data_count[6]} {data_count[7]} {data_count[8]} {data_count[9]}]]
connect_debug_port u_ila_0/probe2 [get_nets [list {prot/uart_byte_reg[7][0]} {prot/uart_byte_reg[7][1]} {prot/uart_byte_reg[7][2]} {prot/uart_byte_reg[7][3]} {prot/uart_byte_reg[7][4]} {prot/uart_byte_reg[7][5]} {prot/uart_byte_reg[7][6]} {prot/uart_byte_reg[7][7]}]]
connect_debug_port dbg_hub/clk [get_nets uart_sampling_clk_BUFG]


create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 65536 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list ck/clock_i/clk_wiz_0/inst/clk_out3]]
set_property port_width 10 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {prot/data_count[0]} {prot/data_count[1]} {prot/data_count[2]} {prot/data_count[3]} {prot/data_count[4]} {prot/data_count[5]} {prot/data_count[6]} {prot/data_count[7]} {prot/data_count[8]} {prot/data_count[9]}]]
create_debug_port u_ila_0 probe
set_property port_width 1 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {recv/D[0]}]]
create_debug_port u_ila_0 probe
set_property port_width 1 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {recv/USB_RX[0]}]]
create_debug_port u_ila_0 probe
set_property port_width 8 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {recv/uart_byte[0]} {recv/uart_byte[1]} {recv/uart_byte[2]} {recv/uart_byte[3]} {recv/uart_byte[4]} {recv/uart_byte[5]} {recv/uart_byte[6]} {recv/uart_byte[7]}]]
create_debug_port u_ila_0 probe
set_property port_width 8 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list {prot/D[0]} {prot/D[1]} {prot/D[2]} {prot/D[3]} {prot/D[4]} {prot/D[5]} {prot/D[6]} {prot/D[7]}]]
create_debug_port u_ila_0 probe
set_property port_width 3 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list {prot/cs[0]} {prot/cs[1]} {prot/cs[2]}]]
create_debug_port u_ila_0 probe
set_property port_width 1 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list recv/byte_ready]]
create_debug_port u_ila_0 probe
set_property port_width 1 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list prot/shift_image_reg]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets uart_sampling_clk]
