# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7vx485tffg1761-2

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.cache/wt [current_project]
set_property parent.project_path /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:vc707:part0:1.2 [current_project]
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/init_1.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/init_0.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/0_0.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/0_1.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/0_2.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/0_3.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/0_4.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/0_5.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/0_6.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/0_7.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/0_8.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/0_9.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/0_10.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/0_11.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/0_12.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/0_13.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/0_14.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/0_15.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/0_16.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/0_17.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/0_18.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/0_19.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/0_20.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/0_21.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/0_22.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/0_23.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/0_24.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/0_25.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/0_26.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/0_27.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/0_28.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/0_29.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/0_30.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/0_31.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/0_32.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/0_33.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/0_34.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/0_35.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/0_36.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/0_37.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/0_38.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/0_39.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/0_40.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/0_41.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/0_42.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/0_43.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/0_44.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/0_45.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/0_46.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/0_47.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/0_48.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/0_49.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/0_50.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/0_51.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/0_52.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/0_53.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/0_54.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/0_55.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/0_56.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/0_57.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/0_58.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/0_59.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/0_60.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/0_61.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/0_62.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/0_63.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/0_64.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/0_65.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/0_66.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/0_67.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/0_68.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/0_69.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/0_70.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/0_71.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/0_72.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/0_73.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/0_74.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/0_75.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/0_76.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/0_77.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/0_78.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/0_79.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/0_80.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/0_81.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/0_82.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/0_83.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/0_84.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/0_85.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/0_86.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/0_87.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/0_88.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/0_89.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/0_90.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/0_91.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/0_92.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/0_93.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/0_94.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/0_95.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/0_96.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/0_97.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/0_98.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/0_99.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/0_100.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/0_101.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/0_102.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/0_103.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/0_104.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/0_105.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/0_106.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/0_107.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/0_108.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/0_109.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/0_110.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/0_111.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/0_112.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/0_113.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/0_114.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/0_115.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/0_116.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/0_117.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/0_118.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/0_119.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/0_120.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/0_121.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/0_122.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/0_123.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/0_124.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/0_125.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/0_126.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/0_127.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/1_0.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/1_1.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/1_2.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/1_3.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/1_4.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/1_5.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/1_6.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/1_7.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/1_8.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/1_9.coe
add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_1/weights_layer_1.bd
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_1/ip/weights_layer_1_blk_mem_gen_0_0/weights_layer_1_blk_mem_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_1/ip/weights_layer_1_blk_mem_gen_0_1/weights_layer_1_blk_mem_gen_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_1/ip/weights_layer_1_blk_mem_gen_0_2/weights_layer_1_blk_mem_gen_0_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_1/ip/weights_layer_1_blk_mem_gen_0_3/weights_layer_1_blk_mem_gen_0_3_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_1/ip/weights_layer_1_blk_mem_gen_0_4/weights_layer_1_blk_mem_gen_0_4_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_1/ip/weights_layer_1_blk_mem_gen_0_5/weights_layer_1_blk_mem_gen_0_5_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_1/ip/weights_layer_1_blk_mem_gen_0_6/weights_layer_1_blk_mem_gen_0_6_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_1/ip/weights_layer_1_blk_mem_gen_0_7/weights_layer_1_blk_mem_gen_0_7_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_1/ip/weights_layer_1_blk_mem_gen_0_8/weights_layer_1_blk_mem_gen_0_8_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_1/ip/weights_layer_1_blk_mem_gen_0_9/weights_layer_1_blk_mem_gen_0_9_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_1/weights_layer_1_ooc.xdc]
set_property is_locked true [get_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_1/weights_layer_1.bd]

add_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/weights_layer_0.bd
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/ip/weights_layer_0_blk_mem_gen_0_0/weights_layer_0_blk_mem_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/ip/weights_layer_0_blk_mem_gen_0_2/weights_layer_0_blk_mem_gen_0_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/ip/weights_layer_0_blk_mem_gen_1_2/weights_layer_0_blk_mem_gen_1_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/ip/weights_layer_0_blk_mem_gen_1_3/weights_layer_0_blk_mem_gen_1_3_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/ip/weights_layer_0_blk_mem_gen_3_0/weights_layer_0_blk_mem_gen_3_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/ip/weights_layer_0_blk_mem_gen_3_1/weights_layer_0_blk_mem_gen_3_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/ip/weights_layer_0_blk_mem_gen_3_2/weights_layer_0_blk_mem_gen_3_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/ip/weights_layer_0_blk_mem_gen_3_3/weights_layer_0_blk_mem_gen_3_3_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/ip/weights_layer_0_blk_mem_gen_3_4/weights_layer_0_blk_mem_gen_3_4_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/ip/weights_layer_0_blk_mem_gen_3_5/weights_layer_0_blk_mem_gen_3_5_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/ip/weights_layer_0_blk_mem_gen_3_6/weights_layer_0_blk_mem_gen_3_6_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/ip/weights_layer_0_blk_mem_gen_3_7/weights_layer_0_blk_mem_gen_3_7_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/ip/weights_layer_0_blk_mem_gen_3_8/weights_layer_0_blk_mem_gen_3_8_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/ip/weights_layer_0_blk_mem_gen_3_9/weights_layer_0_blk_mem_gen_3_9_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/ip/weights_layer_0_blk_mem_gen_3_10/weights_layer_0_blk_mem_gen_3_10_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/ip/weights_layer_0_blk_mem_gen_14_0/weights_layer_0_blk_mem_gen_14_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/ip/weights_layer_0_blk_mem_gen_14_1/weights_layer_0_blk_mem_gen_14_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/ip/weights_layer_0_blk_mem_gen_14_2/weights_layer_0_blk_mem_gen_14_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/ip/weights_layer_0_blk_mem_gen_14_3/weights_layer_0_blk_mem_gen_14_3_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/ip/weights_layer_0_blk_mem_gen_14_4/weights_layer_0_blk_mem_gen_14_4_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/ip/weights_layer_0_blk_mem_gen_14_5/weights_layer_0_blk_mem_gen_14_5_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/ip/weights_layer_0_blk_mem_gen_14_6/weights_layer_0_blk_mem_gen_14_6_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/ip/weights_layer_0_blk_mem_gen_14_7/weights_layer_0_blk_mem_gen_14_7_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/ip/weights_layer_0_blk_mem_gen_14_8/weights_layer_0_blk_mem_gen_14_8_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/ip/weights_layer_0_blk_mem_gen_14_9/weights_layer_0_blk_mem_gen_14_9_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/ip/weights_layer_0_blk_mem_gen_14_10/weights_layer_0_blk_mem_gen_14_10_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/ip/weights_layer_0_blk_mem_gen_1_0/weights_layer_0_blk_mem_gen_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/ip/weights_layer_0_blk_mem_gen_26_0/weights_layer_0_blk_mem_gen_26_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/ip/weights_layer_0_blk_mem_gen_27_0/weights_layer_0_blk_mem_gen_27_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/ip/weights_layer_0_blk_mem_gen_27_1/weights_layer_0_blk_mem_gen_27_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/ip/weights_layer_0_blk_mem_gen_27_2/weights_layer_0_blk_mem_gen_27_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/ip/weights_layer_0_blk_mem_gen_27_3/weights_layer_0_blk_mem_gen_27_3_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/ip/weights_layer_0_blk_mem_gen_27_4/weights_layer_0_blk_mem_gen_27_4_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/ip/weights_layer_0_blk_mem_gen_27_5/weights_layer_0_blk_mem_gen_27_5_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/ip/weights_layer_0_blk_mem_gen_27_6/weights_layer_0_blk_mem_gen_27_6_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/ip/weights_layer_0_blk_mem_gen_27_7/weights_layer_0_blk_mem_gen_27_7_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/ip/weights_layer_0_blk_mem_gen_27_8/weights_layer_0_blk_mem_gen_27_8_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/ip/weights_layer_0_blk_mem_gen_27_9/weights_layer_0_blk_mem_gen_27_9_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/ip/weights_layer_0_blk_mem_gen_27_10/weights_layer_0_blk_mem_gen_27_10_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/ip/weights_layer_0_blk_mem_gen_27_11/weights_layer_0_blk_mem_gen_27_11_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/ip/weights_layer_0_blk_mem_gen_27_12/weights_layer_0_blk_mem_gen_27_12_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/ip/weights_layer_0_blk_mem_gen_27_13/weights_layer_0_blk_mem_gen_27_13_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/ip/weights_layer_0_blk_mem_gen_27_14/weights_layer_0_blk_mem_gen_27_14_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/ip/weights_layer_0_blk_mem_gen_27_15/weights_layer_0_blk_mem_gen_27_15_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/ip/weights_layer_0_blk_mem_gen_27_16/weights_layer_0_blk_mem_gen_27_16_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/ip/weights_layer_0_blk_mem_gen_27_17/weights_layer_0_blk_mem_gen_27_17_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/ip/weights_layer_0_blk_mem_gen_27_18/weights_layer_0_blk_mem_gen_27_18_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/ip/weights_layer_0_blk_mem_gen_27_19/weights_layer_0_blk_mem_gen_27_19_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/ip/weights_layer_0_blk_mem_gen_27_20/weights_layer_0_blk_mem_gen_27_20_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/ip/weights_layer_0_blk_mem_gen_27_21/weights_layer_0_blk_mem_gen_27_21_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/ip/weights_layer_0_blk_mem_gen_27_22/weights_layer_0_blk_mem_gen_27_22_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/ip/weights_layer_0_blk_mem_gen_27_23/weights_layer_0_blk_mem_gen_27_23_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/ip/weights_layer_0_blk_mem_gen_27_24/weights_layer_0_blk_mem_gen_27_24_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/ip/weights_layer_0_blk_mem_gen_27_25/weights_layer_0_blk_mem_gen_27_25_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/ip/weights_layer_0_blk_mem_gen_27_26/weights_layer_0_blk_mem_gen_27_26_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/ip/weights_layer_0_blk_mem_gen_27_27/weights_layer_0_blk_mem_gen_27_27_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/ip/weights_layer_0_blk_mem_gen_27_28/weights_layer_0_blk_mem_gen_27_28_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/ip/weights_layer_0_blk_mem_gen_27_29/weights_layer_0_blk_mem_gen_27_29_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/ip/weights_layer_0_blk_mem_gen_27_30/weights_layer_0_blk_mem_gen_27_30_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/ip/weights_layer_0_blk_mem_gen_27_31/weights_layer_0_blk_mem_gen_27_31_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/ip/weights_layer_0_blk_mem_gen_27_32/weights_layer_0_blk_mem_gen_27_32_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/ip/weights_layer_0_blk_mem_gen_27_33/weights_layer_0_blk_mem_gen_27_33_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/ip/weights_layer_0_blk_mem_gen_27_34/weights_layer_0_blk_mem_gen_27_34_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/ip/weights_layer_0_blk_mem_gen_27_35/weights_layer_0_blk_mem_gen_27_35_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/ip/weights_layer_0_blk_mem_gen_27_36/weights_layer_0_blk_mem_gen_27_36_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/ip/weights_layer_0_blk_mem_gen_27_37/weights_layer_0_blk_mem_gen_27_37_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/ip/weights_layer_0_blk_mem_gen_27_38/weights_layer_0_blk_mem_gen_27_38_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/ip/weights_layer_0_blk_mem_gen_27_39/weights_layer_0_blk_mem_gen_27_39_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/ip/weights_layer_0_blk_mem_gen_27_40/weights_layer_0_blk_mem_gen_27_40_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/ip/weights_layer_0_blk_mem_gen_27_41/weights_layer_0_blk_mem_gen_27_41_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/ip/weights_layer_0_blk_mem_gen_27_42/weights_layer_0_blk_mem_gen_27_42_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/ip/weights_layer_0_blk_mem_gen_27_43/weights_layer_0_blk_mem_gen_27_43_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/ip/weights_layer_0_blk_mem_gen_27_44/weights_layer_0_blk_mem_gen_27_44_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/ip/weights_layer_0_blk_mem_gen_27_45/weights_layer_0_blk_mem_gen_27_45_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/ip/weights_layer_0_blk_mem_gen_27_46/weights_layer_0_blk_mem_gen_27_46_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/ip/weights_layer_0_blk_mem_gen_27_47/weights_layer_0_blk_mem_gen_27_47_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/ip/weights_layer_0_blk_mem_gen_27_48/weights_layer_0_blk_mem_gen_27_48_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/ip/weights_layer_0_blk_mem_gen_27_49/weights_layer_0_blk_mem_gen_27_49_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/ip/weights_layer_0_blk_mem_gen_27_50/weights_layer_0_blk_mem_gen_27_50_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/ip/weights_layer_0_blk_mem_gen_27_51/weights_layer_0_blk_mem_gen_27_51_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/ip/weights_layer_0_blk_mem_gen_27_52/weights_layer_0_blk_mem_gen_27_52_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/ip/weights_layer_0_blk_mem_gen_27_53/weights_layer_0_blk_mem_gen_27_53_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/ip/weights_layer_0_blk_mem_gen_27_54/weights_layer_0_blk_mem_gen_27_54_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/ip/weights_layer_0_blk_mem_gen_27_55/weights_layer_0_blk_mem_gen_27_55_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/ip/weights_layer_0_blk_mem_gen_27_56/weights_layer_0_blk_mem_gen_27_56_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/ip/weights_layer_0_blk_mem_gen_27_57/weights_layer_0_blk_mem_gen_27_57_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/ip/weights_layer_0_blk_mem_gen_27_58/weights_layer_0_blk_mem_gen_27_58_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/ip/weights_layer_0_blk_mem_gen_27_59/weights_layer_0_blk_mem_gen_27_59_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/ip/weights_layer_0_blk_mem_gen_27_60/weights_layer_0_blk_mem_gen_27_60_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/ip/weights_layer_0_blk_mem_gen_27_61/weights_layer_0_blk_mem_gen_27_61_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/ip/weights_layer_0_blk_mem_gen_27_62/weights_layer_0_blk_mem_gen_27_62_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/ip/weights_layer_0_blk_mem_gen_27_63/weights_layer_0_blk_mem_gen_27_63_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/ip/weights_layer_0_blk_mem_gen_27_64/weights_layer_0_blk_mem_gen_27_64_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/ip/weights_layer_0_blk_mem_gen_27_65/weights_layer_0_blk_mem_gen_27_65_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/ip/weights_layer_0_blk_mem_gen_27_66/weights_layer_0_blk_mem_gen_27_66_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/ip/weights_layer_0_blk_mem_gen_27_67/weights_layer_0_blk_mem_gen_27_67_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/ip/weights_layer_0_blk_mem_gen_27_68/weights_layer_0_blk_mem_gen_27_68_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/ip/weights_layer_0_blk_mem_gen_27_69/weights_layer_0_blk_mem_gen_27_69_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/ip/weights_layer_0_blk_mem_gen_27_70/weights_layer_0_blk_mem_gen_27_70_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/ip/weights_layer_0_blk_mem_gen_27_71/weights_layer_0_blk_mem_gen_27_71_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/ip/weights_layer_0_blk_mem_gen_27_72/weights_layer_0_blk_mem_gen_27_72_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/ip/weights_layer_0_blk_mem_gen_27_73/weights_layer_0_blk_mem_gen_27_73_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/ip/weights_layer_0_blk_mem_gen_27_74/weights_layer_0_blk_mem_gen_27_74_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/ip/weights_layer_0_blk_mem_gen_27_75/weights_layer_0_blk_mem_gen_27_75_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/ip/weights_layer_0_blk_mem_gen_27_76/weights_layer_0_blk_mem_gen_27_76_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/ip/weights_layer_0_blk_mem_gen_27_77/weights_layer_0_blk_mem_gen_27_77_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/ip/weights_layer_0_blk_mem_gen_27_78/weights_layer_0_blk_mem_gen_27_78_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/ip/weights_layer_0_blk_mem_gen_27_79/weights_layer_0_blk_mem_gen_27_79_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/ip/weights_layer_0_blk_mem_gen_27_80/weights_layer_0_blk_mem_gen_27_80_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/ip/weights_layer_0_blk_mem_gen_27_81/weights_layer_0_blk_mem_gen_27_81_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/ip/weights_layer_0_blk_mem_gen_27_82/weights_layer_0_blk_mem_gen_27_82_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/ip/weights_layer_0_blk_mem_gen_27_83/weights_layer_0_blk_mem_gen_27_83_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/ip/weights_layer_0_blk_mem_gen_27_84/weights_layer_0_blk_mem_gen_27_84_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/ip/weights_layer_0_blk_mem_gen_27_85/weights_layer_0_blk_mem_gen_27_85_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/ip/weights_layer_0_blk_mem_gen_27_86/weights_layer_0_blk_mem_gen_27_86_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/ip/weights_layer_0_blk_mem_gen_27_87/weights_layer_0_blk_mem_gen_27_87_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/ip/weights_layer_0_blk_mem_gen_27_88/weights_layer_0_blk_mem_gen_27_88_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/ip/weights_layer_0_blk_mem_gen_27_89/weights_layer_0_blk_mem_gen_27_89_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/ip/weights_layer_0_blk_mem_gen_27_90/weights_layer_0_blk_mem_gen_27_90_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/ip/weights_layer_0_blk_mem_gen_27_91/weights_layer_0_blk_mem_gen_27_91_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/ip/weights_layer_0_blk_mem_gen_27_92/weights_layer_0_blk_mem_gen_27_92_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/ip/weights_layer_0_blk_mem_gen_27_93/weights_layer_0_blk_mem_gen_27_93_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/ip/weights_layer_0_blk_mem_gen_27_94/weights_layer_0_blk_mem_gen_27_94_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/ip/weights_layer_0_blk_mem_gen_27_95/weights_layer_0_blk_mem_gen_27_95_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/ip/weights_layer_0_blk_mem_gen_27_96/weights_layer_0_blk_mem_gen_27_96_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/ip/weights_layer_0_blk_mem_gen_27_97/weights_layer_0_blk_mem_gen_27_97_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/ip/weights_layer_0_blk_mem_gen_27_98/weights_layer_0_blk_mem_gen_27_98_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/ip/weights_layer_0_blk_mem_gen_27_99/weights_layer_0_blk_mem_gen_27_99_ooc.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/weights_layer_0_ooc.xdc]
set_property is_locked true [get_files /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/weights_layer_0.bd]

read_verilog -library xil_defaultlib -sv /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/new/weight.sv
read_verilog -library xil_defaultlib {
  /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_1/hdl/weights_layer_1_wrapper.v
  /afs/ece.cmu.edu/usr/dongjoop/Desktop/weightProject_FP/weight/weight.srcs/sources_1/bd/weights_layer_0/hdl/weights_layer_0_wrapper.v
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top weights -part xc7vx485tffg1761-2
write_checkpoint -noxdef weights.dcp
catch { report_utilization -file weights_utilization_synth.rpt -pb weights_utilization_synth.pb }
